export default [
  {
    state_name: "Alaska",
    party: "R",
    name: "Daniel Sullivan",
    gender: "male",
    date_of_birth: "1964-11-13",
  },
  {
    state_name: "Alaska",
    party: "R",
    name: "Lisa Murkowski",
    gender: "female",
    date_of_birth: "1957-05-22",
  },
  {
    state_name: "Alabama",
    party: "D",
    name: "Gordon Jones",
    gender: "male",
    date_of_birth: "1954-05-04",
  },
  {
    state_name: "Alabama",
    party: "R",
    name: "Richard Shelby",
    gender: "male",
    date_of_birth: "1934-05-06",
  },
  {
    state_name: "Arkansas",
    party: "R",
    name: "John Boozman",
    gender: "male",
    date_of_birth: "1950-12-10",
  },
  {
    state_name: "Arkansas",
    party: "R",
    name: "Tom Cotton",
    gender: "male",
    date_of_birth: "1977-05-13",
  },

  {
    state_name: "Pennsylvania",
    party: "R",
    name: "Patrick Toomey",
    gender: "male",
    date_of_birth: "1961-11-17",
  },
  {
    state_name: "Pennsylvania",
    party: "D",
    name: "Robert Casey",
    gender: "male",
    date_of_birth: "1960-04-13",
  },
  {
    state_name: "Rhode Island",
    party: "D",
    name: "Jack Reed",
    gender: "male",
    date_of_birth: "1949-11-12",
  },
  {
    state_name: "Rhode Island",
    party: "D",
    name: "Sheldon Whitehouse",
    gender: "male",
    date_of_birth: "1955-10-20",
  },
  {
    state_name: "South Carolina",
    party: "R",
    name: "Lindsey Graham",
    gender: "male",
    date_of_birth: "1955-07-09",
  },
  {
    state_name: "South Carolina",
    party: "R",
    name: "Tim Scott",
    gender: "male",
    date_of_birth: "1965-09-19",
  },
  {
    state_name: "South Dakota",
    party: "R",
    name: "John Thune",
    gender: "male",
    date_of_birth: "1961-01-07",
  },
  {
    state_name: "South Dakota",
    party: "R",
    name: "Mike Rounds",
    gender: "male",
    date_of_birth: "1954-10-24",
  },
  {
    state_name: "Tennessee",
    party: "R",
    name: "Marsha Blackburn",
    gender: "female",
    date_of_birth: "1952-06-06",
  },
  {
    state_name: "Tennessee",
    party: "R",
    name: "Lamar Alexander",
    gender: "male",
    date_of_birth: "1940-07-03",
  },
  {
    state_name: "Texas",
    party: "R",
    name: "John Cornyn",
    gender: "male",
    date_of_birth: "1952-02-02",
  },
  {
    state_name: "Texas",
    party: "R",
    name: "Ted Cruz",
    gender: "male",
    date_of_birth: "1970-12-22",
  },
  {
    state_name: "Utah",
    party: "R",
    name: "Mike Lee",
    gender: "male",
    date_of_birth: "1971-06-04",
  },
  {
    state_name: "Utah",
    party: "R",
    name: "Mitt Romney",
    gender: "male",
    date_of_birth: "1947-03-12",
  },
  {
    state_name: "Virginia",
    party: "D",
    name: "Mark Warner",
    gender: "male",
    date_of_birth: "1954-12-15",
  },
  {
    state_name: "Virginia",
    party: "D",
    name: "Tim Kaine",
    gender: "male",
    date_of_birth: "1958-02-26",
  },
  {
    state_name: "Vermont",
    party: "I",
    name: "Bernard Sanders",
    gender: "male",
    date_of_birth: "1941-09-08",
  },
  {
    state_name: "Vermont",
    party: "D",
    name: "Patrick Leahy",
    gender: "male",
    date_of_birth: "1940-03-31",
  },
  {
    state_name: "Washington",
    party: "D",
    name: "Maria Cantwell",
    gender: "female",
    date_of_birth: "1958-10-13",
  },
  {
    state_name: "Washington",
    party: "D",
    name: "Patty Murray",
    gender: "female",
    date_of_birth: "1950-10-11",
  },
  {
    state_name: "Wisconsin",
    party: "R",
    name: "Ron Johnson",
    gender: "male",
    date_of_birth: "1955-04-08",
  },
  {
    state_name: "Wisconsin",
    party: "D",
    name: "Tammy Baldwin",
    gender: "female",
    date_of_birth: "1962-02-11",
  },
  {
    state_name: "West Virginia",
    party: "D",
    name: "Joe Manchin",
    gender: "male",
    date_of_birth: "1947-08-24",
  },
  {
    state_name: "West Virginia",
    party: "R",
    name: "Shelley Capito",
    gender: "female",
    date_of_birth: "1953-11-26",
  },
  {
    state_name: "Wyoming",
    party: "R",
    name: "John Barrasso",
    gender: "male",
    date_of_birth: "1952-07-21",
  },
  {
    state_name: "Wyoming",
    party: "R",
    name: "Michael Enzi",
    gender: "male",
    date_of_birth: "1944-02-01",
  },
];
